version: "3.3"

services:
  api:
    image: 127.0.0.1:5000/ssr-grpc:api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "50051:50051"
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    image: 127.0.0.1:5000/ssr-grpc:client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  db1:
    image: cassandra
    networks:
      - network_cassandra
    ports:
      - 7000:7000
      - 7001:7001
      - 9162:9162
      - 10000:9042
    volumes:
      - cassanda_data_1:/var/lib/cassandra
      # - ./cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      - CASSANDRA_SEEDS=db1,db2
  db2:
    image: cassandra
    networks:
      - network_cassandra
    volumes:
      - cassanda_data_2:/var/lib/cassandra
      # - ./cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    ports:
      - 10001:9042
    environment:
      - CASSANDRA_SEEDS=db1,db2
volumes:
  cassanda_data_1:
  cassanda_data_2:

networks:
  network_cassandra:
    driver: bridge
